<a href="https://colab.research.google.com/github/aso1901102/AI_tech2020/blob/master/20201009AI0205_selectAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###sklearnによるエラーなので前のバージョンで用意する

In [ ]:
#現在のsklearnをcolabのVMからアンインストール
#!pip uninstall scikit-learn
#前のバージョンを指定してVMにインストール
#!pip install scikit-learn==0.20 --ignore-installed

all_estimators()でループして各種アルゴリズムを比較

In [ ]:
#ライブラリのインポート
import pandas as pd
#学習用とテスト用でデータを分割するらいぶらり
from sklearn.model_selection import train_test_split
#正答数を算出するライブラリ
from sklearn.metrics import accuracy_score
#all_estimators（推定器を全て使えるようになる）
from sklearn.utils.testing import all_estimators
#警告クラス
import warnings

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
  warnings.warn(message, FutureWarning)


webからアヤメのデータを読み込む

In [ ]:
# urlリンクから読み込むライブラリ
import urllib.request as req
#URLの変数を定義する
url = "https://github.com/pandas-dev/pandas/raw/master/pandas/tests/io/data/csv/iris.csv"
#リンクを保存するためのファイルを定義
iris_data = "iris.csv"
req.urlretrieve(url,iris_data)
#DLしたファイルの内容を表示
#アヤメデータの読み込み
iris_data = pd.read_csv(iris_data,encoding="utf-8")
iris_data

SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
#アヤメのデータをラベルと入力データに分離
y = iris_data.loc[:,"Name"];
x = iris_data.loc[:,["SepalLength","SepalWidth","PetalLength","PetalWidth"]]

#学習用とテスト用に分離
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,train_size = 0.8, shuffle = True)


In [ ]:
#warningを無視する
warnings.filterwarnings('ignore')
#classifierのアルゴリズム全てを取得
allAlgrithms = all_estimators(type_filter="classifier")

for(name, algorithm) in allAlgrithms:
  #pythonでのtry-catch(try-except)
  try:
    #アルゴリズムのオブジェクトを作成
    clf = algorithm()

    #学習して評価する
    clf.fit(x_train,y_train)
    y_pred = clf.predict(x_test)
    print(name,"の正解率 = ",accuracy_score(y_test,y_pred))
  #tryここまで
  #pythonのcacth(except)
  except Exception as e:
    print("エラーです。")
    print(e)
  else:
    #print("ERROR無し")
    pass
  #try-cacth(except)終了
#for終了

AdaBoostClassifier の正解率 =  0.9666666666666667
BaggingClassifier の正解率 =  0.9333333333333333
BernoulliNB の正解率 =  0.2
CalibratedClassifierCV の正解率 =  0.9666666666666667
CategoricalNB の正解率 =  0.8666666666666667
エラーです。
could not convert string to float: 'Iris-setosa'
エラーです。
__init__() missing 1 required positional argument: 'base_estimator'
ComplementNB の正解率 =  0.8
DecisionTreeClassifier の正解率 =  0.9333333333333333
DummyClassifier の正解率 =  0.5666666666666667
ExtraTreeClassifier の正解率 =  0.9333333333333333
ExtraTreesClassifier の正解率 =  0.9666666666666667
GaussianNB の正解率 =  0.9666666666666667
GaussianProcessClassifier の正解率 =  0.9333333333333333
GradientBoostingClassifier の正解率 =  0.9333333333333333
HistGradientBoostingClassifier の正解率 =  0.9666666666666667
KNeighborsClassifier の正解率 =  0.9666666666666667
LabelPropagation の正解率 =  0.9666666666666667
LabelSpreading の正解率 =  0.9666666666666667
LinearDiscriminantAnalysis の正解率 =  1.0
LinearSVC の正解率 =  0.9666666666666667
LogisticRegression の正解率 =  0.96666666

### クロスバリデーション


In [ ]:
# クロスバリデーション関連のライブラリをインポート
# K分割クロスバリデーション（交差検証）のためのライブラリ
from sklearn.model_selection import KFold
# クロスバリデーションスコアを取得する為のオブジェクト
from sklearn.model_selection import cross_val_score

### クロスバリデーションを実行

In [ ]:
# K分割交差検証のインスタンスを生成
kfold_cv = KFold(n_splits = 5, shuffle = True)
# 生成したall_estimatorsのインスタンスをループさせてクロスバリデーション
for(name, algorithm) in allAlgrithms:
  try:
    #各アルゴリズムのインスタンス
    clf = algorithm()
    #score属性のアル学習モデルに絞る
    if hasattr(clf,"score"):
      #クロスバリデーションのスコアを取得
      scores = cross_val_score(clf,x,y,cv = kfold_cv)
      # k = n_splits = 5回分のクロスバリデーションスコアを表示
      print(name,"の正解率　＝　")
      print(scores)
    #ifここまで
  #tryここまで
  except Exception as e:
    #None
    pass
    print(e.args)
  #exceptここまで


AdaBoostClassifier の正解率　＝　
[0.93333333 0.86666667 1.         0.93333333 0.8       ]
BaggingClassifier の正解率　＝　
[0.96666667 0.86666667 0.93333333 0.96666667 0.93333333]
BernoulliNB の正解率　＝　
[0.23333333 0.33333333 0.2        0.26666667 0.3       ]
CalibratedClassifierCV の正解率　＝　
[0.9        0.9        0.96666667 0.93333333 0.86666667]
CategoricalNB の正解率　＝　
[1.         0.93333333 0.96666667 0.9        0.86666667]
CheckingClassifier の正解率　＝　
[nan nan nan nan nan]
("__init__() missing 1 required positional argument: 'base_estimator'",)
ComplementNB の正解率　＝　
[0.66666667 0.66666667 0.63333333 0.76666667 0.6       ]
DecisionTreeClassifier の正解率　＝　
[0.8        1.         0.9        0.93333333 0.96666667]
DummyClassifier の正解率　＝　
[0.3        0.23333333 0.46666667 0.26666667 0.5       ]
ExtraTreeClassifier の正解率　＝　
[0.9        0.83333333 0.93333333 0.93333333 1.        ]
ExtraTreesClassifier の正解率　＝　
[0.96666667 0.96666667 0.93333333 0.96666667 0.96666667]
GaussianNB の正解率　＝　
[0.96666667 1.         1.     

おまけ：cross_val_scoreよりも詳しい結果を取得できるクロスバリデーションオブジェクト
### cross_validate

In [ ]:
#　ライブラリのインポート
from sklearn.model_selection import cross_validate

In [ ]:
# K分割交差検証のインスタンスを生成
kfold_cv = KFold(n_splits = 5, shuffle = True)
# 生成したall_estimatorsのインスタンスをループさせてクロスバリデーション
for(name, algorithm) in allAlgrithms:
  try:
    #各アルゴリズムのインスタンス
    clf = algorithm()
    #score属性のアル学習モデルに絞る
    if hasattr(clf,"score"):
      #クロスバリデーションのスコアを取得
      scores = cross_validate(clf,x,y,cv = kfold_cv)
      # k = n_splits = 5回分のクロスバリデーションスコアを表示
      print(name,"の正解率　＝　")
      print(scores)
    #ifここまで
  #tryここまで
  except Exception as e:
    #None
    pass
    print(e.args)
  #exceptここまで

AdaBoostClassifier の正解率　＝　
{'fit_time': array([0.07756233, 0.0644629 , 0.06465602, 0.07037616, 0.06532979]), 'score_time': array([0.00710726, 0.00676441, 0.00695705, 0.00690889, 0.00677204]), 'test_score': array([0.96666667, 0.96666667, 0.9       , 0.93333333, 0.93333333])}
BaggingClassifier の正解率　＝　
{'fit_time': array([0.01537561, 0.01376963, 0.01365304, 0.01347041, 0.01440167]), 'score_time': array([0.00206876, 0.00207305, 0.00196838, 0.00205016, 0.00253391]), 'test_score': array([1.        , 0.93333333, 0.96666667, 0.93333333, 1.        ])}
BernoulliNB の正解率　＝　
{'fit_time': array([0.0031743 , 0.00265241, 0.0032773 , 0.00299335, 0.0026803 ]), 'score_time': array([0.00124145, 0.00157189, 0.0013845 , 0.00153756, 0.00123811]), 'test_score': array([0.16666667, 0.2       , 0.23333333, 0.3       , 0.23333333])}
CalibratedClassifierCV の正解率　＝　
{'fit_time': array([0.05841398, 0.05827594, 0.0566926 , 0.05500603, 0.05677319]), 'score_time': array([0.00185156, 0.00190568, 0.00186634, 0.00192261, 0

### グリッドサーチで最適なパラメータを探索する

ライブラリをインポート

In [ ]:
#グリッドサーチのオブジェクトクラスをインポート
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

グリッドサーチを実行してパラメータを取得

In [ ]:
# グリッドサーチで試すパラメータのパターン指定を定義する
parameters = [
              # 3つのパラメータ、3パターン
              {"C":[1,10,100,1000],"kernel":["linear"]},
              {"C":[1,10,100,1000],"kernel":["rbf"],"gamma":[0.001,0.0001]},
              {"C":[1,10,100,1000],"kernel":["sigmoid"],"gamma":[0.001,0.0001]}
]

#normal learn
clf = SVC()
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print("普通の学習の正解率　＝　",accuracy_score(y_test,y_pred))

# run grid search 
# make of Ksplit cross validate instance
kfold_cv = KFold(n_splits=5,shuffle=True)

#run k split cross validate in grid search
clf_grid = GridSearchCV(SVC(),parameters,cv = kfold_cv)
clf_grid.fit(x_train,y_train)

#Already learned model set last parametor,and print
print("最適なパラメータ　=　",clf_grid.best_estimator_)

#model already set best parametor to evolve
y_pred = clf_grid.predict(x_test)
print ("グリッドサーチの正解率 = ",accuracy_score(y_test,y_pred))

普通の学習の正解率　＝　 0.9
最適なパラメータ　=　 SVC(C=1000, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
グリッドサーチの正解率 =  1.0


Numpyの動作確認


In [1]:
import numpy as np

# numpy配列の初期化
#ndarrayというnumpy配列を生成
a = np.array([1,2,3,4,5])
print(a)
#type関数で関数型を表示
print(type(a))

#2次元配列のndarrayを定義
b = np.array([[1,2,3],[4,5,6]])
print(b)

#配列の要素数を指定して初期化状態で作成
#1次元配列
print(np.zeros(10))
#2次元配列
print(np.zeros((3,2)))

#配列の中身を１で初期化
print(np.ones(3))

#配列の中身を要素数で初期化
print(np.arange(5))

#配列の中身を指定の要素数で初期化
print(np.arange(2,4))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1. 1.]
[0 1 2 3 4]
[2 3]


numpyで行列計算

In [2]:
a = np.array([1,2,3,4,5])
b = a * 2
print(b)

x = np.arange(10)
c = 3 * x + 5
print(c)

# 配列の次元数を表示
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)
print(a.shape)
print(b.shape)

#配列の次元数を変換する
a = np.array([[1,2,3],[4,5,6]])
print(a)
#2次元配列を1次元配列にする
b = a.flatten()
print(b)

#行列反転
c = a.reshape(3,2)#2行3列　→　3行2列
print(c)

[ 2  4  6  8 10]
[ 5  8 11 14 17 20 23 26 29 32]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(2, 3)
(3, 3)
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
